# âœï¸ Description:
# This action is used to run the type-check on the project.
# Runs on pull requests and pushes to  the main/master/develop branches
# Based on the event type:
#   - If it's a pull request, it will run type checking, then add the check to the PR as well as annotate the code with the errors using reviewdog.
#   - If it's a push to main/master/develop, it will run the type checking and fail if there are any errors.

# ğŸš¨ GITHUB SECRETS REQUIRED: GITHUB_TOKEN

name: ğŸ”¬ Type Check (tsc)

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

#Cancel other running jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  type-check:
    name: Type Check (tsc)
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Checkout project repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ğŸ“¦ Setup Project
        uses: ./.github/actions/setup-node-yarn-install

      - name: ğŸ“¦ Install Reviewdog
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-setup@v1

      - name: ğŸƒâ€â™‚ï¸ Run TypeScript PR # Reviewdog tsc errorformat: %f:%l:%c - error TS%n: %m
        # we only need to add the reviewdog step if it's a pull request
        if: github.event_name == 'pull_request'
        run: |
          yarn ts-check | reviewdog -name="tsc" -efm="%f(%l,%c): error TS%n: %m" -reporter="github-pr-review" -filter-mode="nofilter" -fail-on-error -tee
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name:
          ğŸƒâ€â™‚ï¸ Run TypeScript Commit
          # If it's not a Pull Request then we just need to run the type-check
        if: github.event_name != 'pull_request'
        run: yarn ts-check
